### PR TITLE
KSP-100 Refactor register endpoint

### PR DESCRIPTION
**Pull request by navarrojandg**

### CODE REVIEW

**Comment by navarrojandg** [comment]
Wait @jesc0bar please dont hate me lol this has double commits, how can i fix? This PR is not urgent btw.

**Comment by jesc0bar** [comment]
> Wait @jesc0bar please dont hate me lol this has double commits, how can i fix? This PR is not urgent btw.

It's all good. Fixed the refs. Just force update on your end.

**Review by ivancuadra869 — APPROVED** [review]
Tested with Amy, looks great! thanks!

**Review by ameliaabou — APPROVED** [review]
Tested and reviewed, looks good

**Pull request merged**
