### PR TITLE
KSP-31 Setup frontend

### PR DESCRIPTION
**Pull request by navarrojandg**
Frontend is ready to be developed on. Project uses eslint, prettier, and husky to lint and format code on pre-commit git hook, standardizing the project code.

### CODE REVIEW

**Comment by ivancuadra869** [comment]
This is was we discussed earlier huh? Looks great.

**Comment by navarrojandg** [comment]
Yeah, also there is also branch protection on main so I can't merge without your guys' approval lol

**Review by ivancuadra869 — APPROVED** [review]

**Comment by navarrojandg** [comment]
@jesc0bar Can you please formally approve this pr so I can merge with main?

**Review by jesc0bar — APPROVED** [review]
lgtm

**Comment by jesc0bar** [comment]
> 
> 
> @jesc0bar Can you please formally approve this pr so I can merge with main?

Sorry for that. Just approved.

**Pull request merged**
