### PR TITLE
Ksp 99 refactor create event endpoint

### PR DESCRIPTION
**Pull request by ivancuadra869**
Related to #27

### CODE REVIEW

**Comment by navarrojandg** [comment]
Needs functions config to properly init the nodemailer

Need deploy functions:api and make sure create-event endpoint still works

**Comment by navarrojandg** [comment]
Im comfortable now with the changes made to the create-event route however @jesc0bar can you please configure the nodemailer again and then redeploy the functions.

Also some user records would need to be updated, I have messaged those who would be affected via [discord](https://discord.com/channels/885322238071541860/885322238071541863/907965973821288448)

**Comment by ivancuadra869** [comment]
> Im comfortable now with the changes made to the create-event route however @jesc0bar can you please configure the nodemailer again and then redeploy the functions.
> 
> Also some user records would need to be updated, I have messaged those who would be affected via [discord](https://discord.com/channels/885322238071541860/885322238071541863/907965973821288448)

@jesc0bar have you had a chance to take a look at Jan's comment? Just want to know if it's good on your tests.

**Comment by jesc0bar** [comment]
When creating an event I am labeled as a host and guest. Is there a reason for both to exist?

**Comment by jesc0bar** [comment]
> Im comfortable now with the changes made to the create-event route however @jesc0bar can you please configure the nodemailer again and then redeploy the functions.
> 
> Also some user records would need to be updated, I have messaged those who would be affected via [discord](https://discord.com/channels/885322238071541860/885322238071541863/907965973821288448)

I just now updated the functions so this PR is ready for a review.

**Comment by jesc0bar** [comment]
> > Im comfortable now with the changes made to the create-event route however @jesc0bar can you please configure the nodemailer again and then redeploy the functions.
> > Also some user records would need to be updated, I have messaged those who would be affected via [discord](https://discord.com/channels/885322238071541860/885322238071541863/907965973821288448)
> 
> @jesc0bar have you had a chance to take a look at Jan's comment? Just want to know if it's good on your tests.

Yes, I updated the functions. You should now be able to test functionality on your end and check for any breaks.

**Comment by navarrojandg** [comment]
@jesc0bar You have both GUEST and HOST role because you put your own email as part of the guest list. The endpoint takes the guest list and then through the email it finds the uid and then links that event to the user by adding the event to their events field with the GUEST role.

**Comment by jesc0bar** [comment]
Ah yes. Great. Thanks for clearing that up. Didn't know that was part of the new changes.

**Review by jesc0bar — APPROVED** [review]
Lgtm

**Comment by navarrojandg** [comment]
Converted to draft because we will urgently merge KSP-108 first since this branch is dependent on it.

**Review by navarrojandg — APPROVED** [review]

**Pull request merged**
