### PR TITLE
KSP-99 Refactor create-event endpoint

### PR DESCRIPTION
**Pull request by navarrojandg**
Refactored create-event endpoint by creating middleware for each step necessary for the route to complete. This way when an error occurs it is known exactly where the error was thrown and relayed back to the client so the client can retry accordingly. 

Additionally refactored the emailing guests to its own middleware and saved one doc read by hooking into the request body for the guest list rather than getting that data from the doc.

@jesc0bar and @ivancuadra869 I've noticed that both of your user records still have the events field as a map rather than an array. I have yet to deploy this function because I don't know if changing from the events field from map to array will break something in our app. Also Jorge, I do not have the env config set up properly for the nodemailer to create the transport, if you could take care of this on your end that would be sick.

### CODE REVIEW

**Comment by navarrojandg** [comment]
Also this branch is branched off KSP-100 since I finished that one first because it was a simpler refactor vs this one.

**Comment by jesc0bar** [comment]
I'd say let's hold off on the deploy until after Monday so that we can present and avoid any potential issues. 

Also, I can take care of the email function deploy for Monday.

**Review by ivancuadra869 — APPROVED** [review]

**Comment by jesc0bar** [comment]
Are there any known issues other than the events field from the map?
I tested for any breaking changes and the create event crashed. They're in the logs on firebase. 
Time of testing: Nov 3, 2021 5:35pm - 5:41pm.

**Review by mtahery20 — APPROVED** [review]

**Comment by jesc0bar** [comment]
need to re-open this PR for proper review

**Pull request merged**
