### PR TITLE
KSP-157 UI clean up for final submission

### PR DESCRIPTION
**Pull request by navarrojandg**

### CODE REVIEW

**Comment by navarrojandg** [comment]
Please use this branch to consolidate all commits regarding cleaning up the UI.

**Review by ivancuadra869 — APPROVED** [review]
There were a few changes I have recommended, but we will address them after the final presentation.

**Comment by mtahery20** [comment]
Looks great! Everything is working perfectly, we'll make the nav header transparent next semester

**Review by mtahery20 — APPROVED** [review]
Looks great! Everything is working perfectly. We'll make the nav header transparent next semester

**Pull request merged**
