### PR TITLE
refactor: change modal HeatMap to ScheduleSelector

### PR DESCRIPTION
**Pull request by ivancuadra869**
ScheduleSelector allows for click and drag.
Refactored the userAvailability to be Array<Date>.
Also implemented what KSP 90 implements.

### CODE REVIEW

**Comment by ivancuadra869** [comment]
If you plan to test, then you will have to delete your user availability from Firestore and re-add it as array named "availability".

**Comment by navarrojandg** [comment]
Is the styled-components library being used?

**Comment by ivancuadra869** [comment]
I didn't think so, Jorge asked the same thing. I didn't use it.

**Comment by jesc0bar** [comment]
The react-schedule-selector package is requiring styled-components as a peer dependency to avoid version conflicts.

**Review by navarrojandg — APPROVED** [review]
Ivan please walk me through the availability logic another time.

**Review by jesc0bar — APPROVED** [review]

**Pull request merged**
