### PR TITLE
Ksp 159 refactor create event back end

### PR DESCRIPTION
**Pull request by ivancuadra869**
Refactored create event function to use Moment package instead of Native Date.

### CODE REVIEW

**Review by navarrojandg — COMMENTED** [review]
Code looks good to me -- although unsure if the formatAvailability should be in the firebase file

**Comment by ivancuadra869** [comment]
> Code looks good to me -- although unsure if the formatAvailability should be in the firebase file

Agreed, I can refactor that in the KSP we're working on.

**Review by navarrojandg — APPROVED** [review]
Okay sounds good, will approve then.

**Comment by ivancuadra869** [comment]
I transferred these changes over to the new repo.

**Pull request closed without merging**
